---

- name: 'Check mandatory variables are defined'
  assert:
    that:
      - application_name is defined
      - loki_url is defined
      - garments_api_endpoint is defined
      - domain_name is defined

- name: Create app container
  docker_container:
    name: "{{ application_name }}"
    pull: true
    cleanup: true
    image: "namelivia/{{ application_name }}:latest"
    memory: "10MB"
    restart_policy: "always"
    log_driver: "loki"
    log_options:
      loki-url: "{{ loki_url }}"
      loki-batch-size: "400"
    exposed_ports:
      - "80"
    networks:
      - name: "pomerium"
    env:
      VUE_APP_API_ENDPOINT: "{{ garments_api_endpoint }}"
      VIRTUAL_HOST: "{{ domain_name }}"
      VIRTUAL_PATH: "/"
      LETSENCRYPT_HOST: "{{ domain_name }}"
      VIRTUAL_PORT: "80"
